'use strict';

const fs = require('fs-extra');
const path = require('path');
const mkdirp = require('mkdirp');

const webpack = require('webpack');
const ProgressBarPlugin = require('progress-bar-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const OfflinePlugin = require('offline-plugin');

const buildPath = path.join(process.cwd(), 'build');
const publicPath = path.join(process.cwd(), 'public');

const projectRoot = path.resolve(__dirname, '../');

mkdirp.sync(buildPath);

const compiler = webpack({
  entry: [
    './src/'
  ],
  output: {
    filename: 'app.[hash].js',
    path: buildPath
  },
  resolve: {
    alias: {
      '@root': path.join(projectRoot, 'src'),
    },
    extensions: ['.ts', '.tsx', '.js']
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: /node_modules/
      }
    ]
  },
  plugins: [
    new ProgressBarPlugin(),
    new webpack.optimize.UglifyJsPlugin({ minimize: true }),
    new HtmlWebpackPlugin({
      template: path.resolve(projectRoot, 'public', 'index.html')
    }),
    new OfflinePlugin({
      publicPath: '/',
      caches: {
        main: [
          'icons/launcher-zaraina-48x48.png',
          'icons/launcher-zaraina-72x72.png',
          'icons/launcher-zaraina-96x96.png',
          'icons/launcher-zaraina-144x144.png',
          'icons/launcher-zaraina-192x192.png',
          'app.*.js',
        ],
        additional: [
          ':externals:'
        ],
        optional: [
          ':rest:'
        ]
      },
      externals: [
        '/'
      ],
      ServiceWorker: {
        navigateFallbackURL: '/'
      }
    })
  ]
});

compiler.run((err, stats) => {
  if (err) {
    console.log(err);
  } else {
    // Do not copy index.html as it is already generated by html-webpack-plugin.
    fs.copySync(publicPath, buildPath, {
      filter: file => !file.endsWith('index.html')
    });
  }
})
